[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  branch = "master"

[[constraint]]
  name = "github.com/ubccr/goipa"
  branch = "master"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/labstack/echo-contrib"
  version = "0.5.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  name = "github.com/dchest/captcha"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.1"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  branch = "master"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "^2.0.0"

[[constraint]]
  name = "github.com/ory/hydra"
  version = "=v0.9.15"

[[constraint]]
  name = "github.com/pquerna/otp"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "9a379c6b3e95a790ffc43293c2a78dee0d7b6e20"

[[constraint]]
  name = "gopkg.in/coreos/go-oidc.v2"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
