[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  branch = "master"

[[constraint]]
  name = "github.com/ubccr/goipa"
  branch = "master"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/labstack/echo-contrib"
  version = "0.5.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  name = "github.com/dchest/captcha"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.1"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  branch = "master"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "^2.0.0"

[prune]
  go-tests = true
  unused-packages = true
