name: Build test Mokey Docker image

on:
  pull_request:
  workflow_dispatch:

jobs:
  Build-Test-Sneaklardooon-Docker-image:
    name: Build Mokey and Docker image.
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Get current date
          id: date
          run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

        - name: Build image only
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
